server:
  port: 8090
#spring:
#  datasource:
#    password: 123456
docker:
  host: tcp://123.57.52.207:2376
  tls_verify: true
  cert_path: classpath:ca
  config:
  api_version:
  registry:
    url: https://index.docker.io/v1/
    username: leikooo
    password: Ee719963000
    email: liangzilixue123456@gmail.com
