server:
  port: 8080
spring:
  profiles:
    active: dev
docker:
  host: ${docker.host}
  tls_verify: ${docker.tls_verify}
  registry:
    username: ${docker.registry.username}
    password: ${docker.registry.password}
    email: ${docker.registry.email}
